[theme]
base = "dark"
primaryColor = "#C8FF3D"
backgroundColor = "#09090B"
secondaryBackgroundColor = "#18181B"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
maxUploadSize = 25

[browser]
gatherUsageStats = false

